spring:
  jpa:
 #   show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://host.docker.internal:3308/springbootcrudexample
    username: root
    password: azerty
server:
   port: 9092