spring:
  jpa:
 #   show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/springbootcrudexample?serverTimezone=UTC
    username: root
    password: azerty
server:
   port: 9090